E-Recarga/E-Recarga/Models/ERecargaModels/Appointment.cs
using E_Recarga.Models.CustomValidators;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace E_Recarga.Models.ERecargaModels
{
    public class Appointment
    {
        [ForeignKey("Company")]
        [Display(Name = "Empresa")]
        public int CompanyId { get; set; }
        public virtual Company Company { get; set; }

        [ForeignKey("Station")]
        [Display(Name = "Estação")]
        public int? StationId { get; set; }
        public virtual Station Station { get; set; }

        [ForeignKey("Pod")]
        [Display(Name = "Posto")]
        public int? PodId { get; set; }
        public virtual Pod Pod { get; set; }

        [ForeignKey("User")]
        [Display(Name = "Utilizador")]
        public string UserId { get; set; }
        public virtual ApplicationUser User { get; set; }

        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        [Display(Name = "Custo")]
        [Range(0.00,double.MaxValue)]
        public double Cost { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        [Display(Name = "Inicio da Marcação")]
        public DateTime Start { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        [Display(Name = "Fim da marcação")]
        public DateTime End { get; set; }

        [ForeignKey("Status")]
        [Display(Name = "Estado da Marcação")]
        public AppointmentStatusEnum AppointmentStatusId { get; set; }
        public virtual AppointmentStatus Status { get; set; }
    }
}

E-Recarga/E-Recarga/Controllers/ERecargaControllers/AppointmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using E_Recarga.Models;
using E_Recarga.Models.ERecargaModels;
using Microsoft.AspNet.Identity;
using E_Recarga.App_Code;
using System.Globalization;
using System.Data.Entity.Validation;

namespace E_Recarga.Controllers.ERecargaControllers
{
    [RoutePrefix("Marcacoes")]
    public class AppointmentsController : Controller
    {
        private ERecargaDbContext db = new ERecargaDbContext();

        // GET: Appointments
        [Authorize(Roles = nameof(RoleEnum.CompanyManager) + ", " + nameof(RoleEnum.Employee))]
        [Route]
        public ActionResult Index(bool viewAll = false, int? id = null)
        {
            var user = db.Employees.Find(User.Identity.GetUserId());

            if (id != null)
            {
                var station = db.Stations.Find(id);
                id = station.CompanyId != user.CompanyId ? null : id;
            }

            List<Appointment> appointments = null;
            if (User.IsInRole(nameof(RoleEnum.CompanyManager)))
            {
                if (viewAll)
                {
                    if (id != null)
                    {
                        appointments = user.Company.Appointments
                            .Where(s => s.StationId == (int)id).ToList();
                    }
                    else
                    {
                        appointments = user.Company.Appointments.ToList();
                    }
                }
                else
                {
                    var dayLimit = DateTime.Now.AddDays(1);

                    if (id != null)
                    {
                        appointments = user.Company.Appointments
                            .Where(ap => ap.AppointmentStatusId == AppointmentStatusEnum.Pending ||
                            ap.AppointmentStatusId == AppointmentStatusEnum.Ongoing &&
                            ap.Start < dayLimit &&
                            ap.StationId == id)
                            .ToList();
                    }
                    else
                    {
                        appointments = user.Company.Appointments
                            .Where(ap => ap.AppointmentStatusId == AppointmentStatusEnum.Pending ||
                            ap.AppointmentStatusId == AppointmentStatusEnum.Ongoing &&
                            ap.Start < dayLimit)
                            .ToList();
                    }
                }
            }
            else
            {
                if (user.StationId == null)
                {
                    return HttpNotFound();
                }

                if (viewAll)
                {
                    appointments = user.Station.Appointments.ToList();
                }
                else
                {
                    var dayLimit = DateTime.Now.AddDays(1);

                    appointments = user.Station.Appointments
                            .Where(ap => ap.AppointmentStatusId == AppointmentStatusEnum.Pending ||
                            ap.AppointmentStatusId == AppointmentStatusEnum.Ongoing &&
                            ap.Start < dayLimit)
                            .ToList();
                }

            }

            appointments.OrderByDescending(a => a.Start);

            return View(appointments.AsQueryable());
        }

        // GET: Appointments/Details/5
        [Route("{id:int}/Detalhes")]
        [Authorize(Roles = nameof(RoleEnum.CompanyManager) + ", " + nameof(RoleEnum.Employee) + ", " + nameof(RoleEnum.User))]
        public ActionResult Details(int id)
        {
            Appointment appointment = db.Appointments.Find(id);
            if (appointment == null)
            {
                return HttpNotFound();
            }

            if (User.IsInRole(nameof(RoleEnum.CompanyManager)))
            {
                var user = db.Employees.Find(User.Identity.GetUserId());
                if (user.CompanyId != appointment.CompanyId)
                {
                    return HttpNotFound();
                }
            }
            else if (User.IsInRole(nameof(RoleEnum.Employee)))
            {
                var user = db.Employees.Find(User.Identity.GetUserId());
                if (user.StationId == null)
                {
                    return HttpNotFound();
                }
            }

            return View(appointment);
        }

        [Route("Utilizador/Agendar")]
        [Authorize(Roles = nameof(RoleEnum.User))]
        public ActionResult UserAppointmentCreate(string initCharge,string endCharge,string podTypeStr,int stationId)
        {
            var user = db.Users.Find(User.Identity.GetUserId());
            if(user.Appointments.Where(x => x.AppointmentStatusId == AppointmentStatusEnum.Pending ||
                                        x.AppointmentStatusId == AppointmentStatusEnum.Ongoing).Count() > 0)
            {
                TempData["msg"] = "Existe outro agendamento, se pretender, elimine-o e crie um novo.";
                return RedirectToAction("AppointmentsRecords", "Users",null);
            }

            var station = db.Stations.Find(stationId);
            var pods = station.Pods.Where(p => p.PodType.Name == podTypeStr && p.isActive);
            var podType = podTypeStr == nameof(PodTypeEnum.Fast) ? PodTypeEnum.Fast : PodTypeEnum.Normal;
            DateTime init;
            DateTime end;

            if (DateTime.TryParseExact(initCharge, "MM/dd/yyyy HH:mm:ss", new CultureInfo("pt-PT", false), DateTimeStyles.None, out init) == false ||
                DateTime.TryParseExact(endCharge, "MM/dd/yyyy HH:mm:ss", new CultureInfo("pt-PT", false), DateTimeStyles.None, out end) == false)
                return View();
                       
            double cost = PriceGenerator.CalculatePrice(init, end, station.Prices, podType);

            if (cost > user.Wallet)
            {
                TempData["msg"] = "Dinheiro insuficiente, para efectuar agendamento tem de conter: " + cost + "€ .";
                return RedirectToAction("AddMoney", "Users", null);
            }

            Pod pod = pods.ToList().Find(p=> (p.Appointments
                            .All(a => a.Start > end.AddMinutes(5) ||
                            a.End.AddMinutes(5) < init) ) ||
                            p.Appointments.Count == 0);

            return View(new Appointment() { Start = init, End = end,Pod = pod ,PodId = pod.Id, Cost = cost,Station = station,Company= station.Company, User = user});
        }

        [Route("Utilizador/Agendar")]
        [Authorize(Roles = nameof(RoleEnum.User))]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult UserAppointmentCreate([Bind(Include = "Start,End,PodId,Cost")]Appointment appointment)
        {
            appointment.AppointmentStatusId = AppointmentStatusEnum.Pending;
            var user = db.Users.Find(User.Identity.GetUserId());
            var pod = db.Pods.Find(appointment.PodId);

            if(pod == null)
            {
                return HttpNotFound();
            }

            appointment.UserId = user.Id;
            appointment.PodId = pod.Id;
            appointment.StationId = pod.StationId;
            appointment.CompanyId = pod.Station.CompanyId;


            if (ModelState.IsValid)
            {
                user.Wallet -= appointment.Cost * 0.15;
                db.Entry(user).State = EntityState.Modified;

                db.Appointments.Add(appointment);
                db.SaveChanges();
                return RedirectToAction("Index","Home",null);
            }
            
            return View(appointment);
        }

        // GET: Appointments/Create
        [Route("Empregado/Agendar")]
        [Authorize(Roles = nameof(RoleEnum.Employee) +  ", "+ nameof(RoleEnum.CompanyManager))]
        public ActionResult Create()
        {
            //recebe employees
            var user = db.Employees.Find(User.Identity.GetUserId());

            ViewBag.StationId = new SelectList(db.Stations.Where(s=>s.CompanyId == user.CompanyId), "Id", "ComercialName");

            List<ApplicationUser> users = new List<ApplicationUser>();
            var db_users = db.Users.ToList();
            foreach (ApplicationUser elem in db_users)
            {
                var roleId = elem.Roles.ToList()[0].RoleId;
                var role = db.Roles.Where(x => x.Id == roleId).FirstOrDefault();

                if(role.Name == nameof(RoleEnum.User))
                    users.Add(elem);
            }
            ViewBag.UserId = new SelectList(users, "Id", "Email"); //TODO: only put users of primary user role

            int companyId = user.CompanyId;
            if(User.IsInRole(nameof(RoleEnum.Employee)) && user.StationId != null)
                return View(new Appointment() { CompanyId = companyId, Company = user.Company,
                    Start = DateTime.Now.AddMinutes(30), End = DateTime.Now.AddHours(5),
                    Station = user.Station, StationId = user.StationId });
            else
                return View(new Appointment()
                {
                    CompanyId = companyId,
                    Company = user.Company,
                    Start = DateTime.Now.AddMinutes(30),
                    End = DateTime.Now.AddHours(5)
                });
        }

        // POST: Appointments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Route("Empregado/Agendar")]

E-Recarga/E-Recarga/Views/Appointments/Create.cshtml
@model E_Recarga.Models.ERecargaModels.Appointment
@using E_Recarga.Models

@{
    ViewBag.Title = "Agendar";
}

<h2>Agendar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Appointment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Company.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Company.Name, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.Company.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        @if (User.IsInRole(nameof(RoleEnum.Employee)) && Model.StationId != null)
        {
            <div class="form-group">
                @Html.LabelFor(model => model.Station.ComercialName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Station.ComercialName, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    @Html.ValidationMessageFor(model => model.Station.ComercialName, "", new { @class = "text-danger" })
                </div>
            </div>
        }
        else
        {
            <div class="form-group">
                @Html.LabelFor(model => model.StationId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("StationId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.StationId, "", new { @class = "text-danger" })
                </div>
            </div>
        }

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Start, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Start, new { @id = "startTime", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Start, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.End, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.End, new { @id = "endTime", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.End, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">

        var today = new Date();
        var _maxDate = today.getDate() + 7;

        $(function (e) {
            $('#startTime').datetimepicker({
                locale: 'pt',
                minDate: today,
                showClose: true,
                showClear: true,
                toolbarPlacement: 'top',
                stepping: 15
            });

            $('#endTime').datetimepicker({
                useCurrent: false, //Important! See issue #1075
                locale: 'pt',
                minDate: today,
                showClose: true,
                showClear: true,
                toolbarPlacement: 'top',
                stepping: 30
            });


            $("#startTime").on("dp.change", function (e) {
                $('#endTime').data("DateTimePicker").minDate(e.date);
                //Adds 5 hours, this is ridiculous
                $('#endTime').data("DateTimePicker").maxDate(new Date(e.date + (5 * 60 * 60 * 1000)));
            });

            $("#endTime").on("dp.change", function (e) {
                $('#startTime').data("DateTimePicker").maxDate(e.date);
            });

            $("#startTime").attr("autocomplete", "off");
            $("#endTime").attr("autocomplete", "off");
        });
    </script>

}

E-Recarga/E-Recarga/Views/Appointments/Delete.cshtml
@model E_Recarga.Models.ERecargaModels.Appointment
@using E_Recarga.Models

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Appointment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Empresa
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Company.Name)
        </dd>

        <dt>
            Estação
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Station.ComercialName)
        </dd>

        <dt>
            Posto
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pod.Identifier)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Start)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Start)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.End)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.End)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status.Name)
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-default" /> | 
        @if (User.IsInRole(nameof(RoleEnum.User)))
        {
            @Html.ActionLink("Voltar", "AppointmentsRecords", "Users", null, null);
        }
        else
        {
            @Html.ActionLink("Voltar", "Index");
        }
    </div>

       
    }
</div>





E-Recarga/E-Recarga/Views/Appointments/Details.cshtml
@model E_Recarga.Models.ERecargaModels.Appointment
@using E_Recarga.Models

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Appointment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Empresa
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Company.Name)
        </dd>

        <dt>
            Estação
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Station.ComercialName)
        </dd>

        <dt>
            Posto
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pod.Identifier)
        </dd>

        <dt>
            Nome do Utilizador
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Start)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Start)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.End)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.End)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status.Name)
        </dd>

    </dl>
</div>

@if (User.IsInRole(nameof(RoleEnum.Employee)))
{
    @Html.ActionLink("Voltar", "Index");
    <span> | </span>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id });
}
else if (User.IsInRole(nameof(RoleEnum.CompanyManager)))
{
    @Html.ActionLink("Voltar", "Index");
}
else
{
    @Html.ActionLink("Voltar", "AppointmentsRecords","Users",null,null);
}

E-Recarga/E-Recarga/Views/Appointments/Edit.cshtml
@model E_Recarga.Models.ERecargaModels.Appointment

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Appointment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Company.Name, "Empresa", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Company.Name, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.Company.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Station.ComercialName, "Estação", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Station.ComercialName, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.Station.ComercialName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pod.Identifier, "Posto", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pod.Identifier, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.Pod.Identifier, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.User.Name, "Nome do utilizador", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.User.Name, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.User.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Start, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Start, new { @id = "startTime", @class = "form-control", @readonly = "readonly" })
                @Html.ValidationMessageFor(model => model.Start, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.End, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.End, new { @id = "endTime", @class = "form-control", @readonly = "readonly" })
                @Html.ValidationMessageFor(model => model.End, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AppointmentStatusId, "Estado", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AppointmentStatusId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AppointmentStatusId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {

}

E-Recarga/E-Recarga/Views/Appointments/UserAppointmentCreate.cshtml
@model E_Recarga.Models.ERecargaModels.Appointment

@{
    ViewBag.Title = "Confirmar Marcação";
}

<br /><br />
<h3>Confirmar Marcação</h3>
<br />
<hr />
<h4>
    Preços da Estação @Html.DisplayFor(model => model.Station.ComercialName)
</h4><br />

@if (Model.Station.Prices == null)
{
    <p>
        Não existem preços definidos para a estação selecionada. A marcação não poderá ser realizada.
    </p>
    <br />
    <div align="right">
        <a href="javascript:void(0);" onclick="history.go(-1);">Cancelar</a>
    </div>
}
else
{
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Station.Prices[0].Time).ToString()
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Station.Prices[0].CostNormal).ToString()
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Station.Prices[0].CostUltra).ToString()
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model.Station.Prices)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Time)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CostNormal)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CostUltra)
                </td>
            </tr>
        }
    </table>
    <br />
}
<br />

<hr />
<h4>
    Marcação
</h4><br />


@using (Html.BeginForm("UserAppointmentCreate", "Appointments", FormMethod.Post))
{
    @Html.AntiForgeryToken()

     <div class="form-horizontal">
         @Html.HiddenFor(x => x.Pod.Id)
         @Html.HiddenFor(x => x.PodId)
         @*<h4>Appointment</h4>
        <hr />*@
         @Html.ValidationSummary(true, "", new { @class = "text-danger" })
         <div class="form-group">
             @Html.LabelFor(model => model.Company.Name, "Company", htmlAttributes: new { @class = "control-label col-md-2" })
             <div class="col-md-10">
                 @Html.EditorFor(model => model.Company.Name, Model.Company.Name, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                 @Html.ValidationMessageFor(model => model.Company.Name, "", new { @class = "text-danger" })
             </div>
         </div>

         <div class="form-group">
             @Html.LabelFor(model => model.Station.ComercialName, "StationId", htmlAttributes: new { @class = "control-label col-md-2" })
             <div class="col-md-10">
                 @Html.EditorFor(model => model.Station.ComercialName, Model.Station.ComercialName, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                 @Html.ValidationMessageFor(model => model.Station.ComercialName, "", new { @class = "text-danger" })
             </div>
         </div>

         <div class="form-group">
             @Html.LabelFor(model => model.Pod.PodType.Id, "Pod", htmlAttributes: new { @class = "control-label col-md-2" })
             <div class="col-md-10">
                 @Html.EditorFor(model => model.Pod.PodType.Id, nameof(Model.Pod.PodType.Id), new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                 @Html.ValidationMessageFor(model => model.Pod.PodType.Id, "", new { @class = "text-danger" })
             </div>
         </div>

         <div class="form-group">
             @Html.LabelFor(model => model.Cost, htmlAttributes: new { @class = "control-label col-md-2" })
             <div class="col-md-10">
                 @Html.EditorFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                 @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })
             </div>
         </div>

         <div class="form-group">
             @Html.LabelFor(model => model.Start, htmlAttributes: new { @class = "control-label col-md-2" })
             <div class="col-md-10">
                 @Html.EditorFor(model => model.Start, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                 @Html.ValidationMessageFor(model => model.Start, "", new { @class = "text-danger" })
             </div>
         </div>

         <div class="form-group">
             @Html.LabelFor(model => model.End, htmlAttributes: new { @class = "control-label col-md-2" })
             <div class="col-md-10">
                 @Html.EditorFor(model => model.End, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                 @Html.ValidationMessageFor(model => model.End, "", new { @class = "text-danger" })
             </div>
         </div>
         <br /><br />
         <div class="form-group" align="right">
             <a href="javascript:void(0);" onclick="history.go(-1);">Cancelar</a>
             @*@if (Model.Station.Prices.Count() != 0)
            {*@
             <span>  |  </span>
             <input type="submit" value="Guardar" class="btn btn-success" />
             @*}*@
         </div>
     </div>
}